In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [33]:
import json
import csv
import pandas as pd
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder

In [34]:
!pip install pypandoc

In [35]:
import pypandoc

def convert_rtf_to_text(file_path):
    output = pypandoc.convert_file(json_file_path, 'plain', format='rtf')
    return output

# Example usage
json_file_path = '/kaggle/input/jason-parsing/algoparams_from_ui.json.rtf'
text = convert_rtf_to_text(json_file_path)

In [36]:
stripped_text = text.replace('\n', '')
text = stripped_text.replace(' ', '')
constraint_dict = json.loads(text)
print(type(constraint_dict))

<class 'dict'>


In [56]:
print(constraint_dict['design_state_data']['feature_handling']['sepal_width']['feature_details']['impute_with'])

custom


In [42]:
class DataLoader:
    def __init__(self, data_file_path):
        self.data_file_path = data_file_path
        self.data = None
        self.X_train, self.X_test, self.y_train, self.y_test = None, None, None, None

    def load_data(self):
        """ Loading the dataset """ 
        self.data = pd.read_csv(self.data_file_path)
        
        # Split the dataset into features and target variable
        X = self.data.drop(columns='species') 
        y = self.data['species']
        
        encoder = LabelEncoder()
        y = encoder.fit_transform(y)
        
        
        # Split the dataset into training and testing sets
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size=0.2, random_state=42)
        print("Data loaded successfully")
    
    def feature_handling(self):
        print("Checking")
        """ Delete columns if is_selected is false """
        if(constraint_dict['design_state_data']['feature_handling']['sepal_length']['is_selected'] == False):
            print("sepal_length False")
            self.X_train = self.X_train.drop('sepal_length', axis = 1)
            self.X_test = self.X_test.drop('sepal_length', axis = 1)
        
        if(constraint_dict['design_state_data']['feature_handling']['sepal_width']['is_selected'] == False):
            print("False")
            self.X_train = self.X_train.drop('sepal_width', axis = 1)
            self.X_test = self.X_test.drop('sepal_width', axis = 1)
            
        if(constraint_dict['design_state_data']['feature_handling']['petal_length']['is_selected'] == False):
            print("False")
            self.X_train = self.X_train.drop('petal_length', axis = 1)
            self.X_test = self.X_test.drop('petal_length', axis = 1)
            
        if(constraint_dict['design_state_data']['feature_handling']['petal_width']['is_selected'] == False):
            print("False")
            self.X_train = self.X_train.drop('petal_width', axis = 1)
            self.X_test = self.X_test.drop('petal_width', axis = 1)
    
    def impute_operations(self):
        """ Impute with mean or custom value. This works only for mean and custom values"""
        print("Imputing")
        if(constraint_dict['design_state_data']['feature_handling']['sepal_length']['feature_details']['impute_with'] == 'Averageofvalues'):
            imputer = SimpleImputer(strategy="mean")
            self.X_train['sepal_length'] = imputer.fit_transform(self.X_train[['sepal_length']])
        elif(constraint_dict['design_state_data']['feature_handling']['sepal_length']['feature_details']['impute_with'] == 'custom'):
            imputer = SimpleImputer(strategy="constant", fill_value=int(constraint_dict['design_state_data']['feature_handling']['sepal_length']['feature_details']['impute_value']))
            self.X_train['sepal_length'] = imputer.fit_transform(self.X_train[['sepal_length']])
            
            
        if(constraint_dict['design_state_data']['feature_handling']['sepal_width']['feature_details']['impute_with'] == 'Averageofvalues'):
            imputer = SimpleImputer(strategy="mean")
            self.X_train['sepal_width'] = imputer.fit_transform(self.X_train[['sepal_width']])
        elif(constraint_dict['design_state_data']['feature_handling']['sepal_width']['feature_details']['impute_with'] == 'custom'):
            imputer = SimpleImputer(strategy="constant", fill_value=int(constraint_dict['design_state_data']['feature_handling']['sepal_width']['feature_details']['impute_value']))
            self.X_train['sepal_width'] = imputer.fit_transform(self.X_train[['sepal_width']])
            
        
        if(constraint_dict['design_state_data']['feature_handling']['petal_length']['feature_details']['impute_with'] == 'Averageofvalues'):
            imputer = SimpleImputer(strategy="mean")
            self.X_train['petal_length'] = imputer.fit_transform(self.X_train[['petal_length']])
        elif(constraint_dict['design_state_data']['feature_handling']['petal_length']['feature_details']['impute_with'] == 'custom'):
            imputer = SimpleImputer(strategy="constant", fill_value=int(constraint_dict['design_state_data']['feature_handling']['petal_length']['feature_details']['impute_value']))
            self.X_train['petal_length'] = imputer.fit_transform(self.X_train[['petal_length']])
            
            
        if(constraint_dict['design_state_data']['feature_handling']['petal_width']['feature_details']['impute_with'] == 'Averageofvalues'):
            imputer = SimpleImputer(strategy="mean")
            self.X_train['petal_width'] = imputer.fit_transform(self.X_train[['petal_width']])
        elif(constraint_dict['design_state_data']['feature_handling']['petal_width']['feature_details']['impute_with'] == 'custom'):
            imputer = SimpleImputer(strategy="constant", fill_value=int(constraint_dict['design_state_data']['feature_handling']['petal_width']['feature_details']['impute_value']))
            self.X_train['petal_width'] = imputer.fit_transform(self.X_train[['petal_width']])
            
            
        
        


In [41]:
data = DataLoader('/kaggle/input/iris-dataset-dendrite/iris.csv')
data.load_data()
data.feature_handling()
data.impute_operations()



Data loaded successfully
Checking
Imputing
     sepal_length  sepal_width  petal_length  petal_width
22            4.6          3.6           1.0          0.2
15            5.7          4.4           1.5          0.4
65            6.7          3.1           4.4          1.4
11            4.8          3.4           1.6          0.2
42            4.4          3.2           1.3          0.2
..            ...          ...           ...          ...
71            6.1          2.8           4.0          1.3
106           4.9          2.5           4.5          1.7
14            5.8          4.0           1.2          0.2
92            5.8          2.6           4.0          1.2
102           7.1          3.0           5.9          2.1

[120 rows x 4 columns]
[1 0 2 1 1 0 1 2 1 1 2 0 0 0 0 1 2 1 1 2 0 2 0 2 2 2 2 2 0 0]


In [94]:
class PipelineData(DataLoader):
    def __init__(self, data_file_path):
        super().__init__(data_file_path)
        self.pipeline_data = Pipeline([])
        print("Data Pipeline Created")
        
    
            
        
        

In [20]:
# pipelineData = PipelineData('/kaggle/input/iris-dataset-dendrite/iris.csv')
# pipelineData.load_data()

Data loaded successfully


In [95]:
class PipelineModel(PipelineData):
    def __init__(self, data_file_path):
        super().__init__(data_file_path)
    
    
    def load_feature_handling():
        super().load_data()
        self.pipeline_model = Pipeline([])
        print("Data and Model Pipeline created successfully")
#         super().feature_handling()
        
    
    
        


In [98]:

model_pipe = PipelineModel('/kaggle/input/iris-dataset-dendrite/iris.csv')
model_pipe.X_train

Data Pipeline Created


In [99]:
print(model_pipe.X_train)

None


In [13]:
import numpy as np
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
print(X)
X = [[np.nan, 2], [6, np.nan], [7, 6]]
imp.fit(X)
print(imp.transform(X))

[[nan, 2], [6, nan], [7, 6]]
[[6.5 2. ]
 [6.  4. ]
 [7.  6. ]]


In [51]:
import scipy.sparse as sp
X = np.array([[1, 0], [0, 8], [8, 4]])
print(X[:,1])
# imp = SimpleImputer(missing_values=0, strategy='mean')
# imp.fit(X[:,1])
# print(imp.transform(X[:,1]))

[0 8 4]


In [67]:
from sklearn.datasets import load_iris
from nltk.tokenize import word_tokenize  # for text tokenization
from sklearn.feature_extraction.text import HashingVectorizer  # for hashing

# Load the iris dataset
iris = load_iris()

# Check the data type of 'species' (should be object for text data)
print(iris.target_names)  # Assuming 'species' is stored in target_names

# No need for separate tokenization as target_names are already single words
species_tokens = iris.target_names  # Assuming each species is a single word

# Hashing with 16 features
hasher = HashingVectorizer(n_features=16)

# Transform tokens (assuming each species is a single word)
hashed_species = hasher.transform(species_tokens)

# Print the hashed features (dense matrix)
print(hashed_species.toarray())


['setosa' 'versicolor' 'virginica']
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [28]:
testdata = pd.read_csv('/kaggle/input/iris-dataset-dendrite/iris.csv')
y = testdata['species']
encoder = LabelEncoder()
encoded_classes = encoder.fit_transform(y)
print(encoded_classes) 
# testdata = testdata.drop('species', axis = 1)
# hasher = HashingVectorizer(n_features=1)
# hashed_target = hasher.transform(np.array(y))
# hashed_target = hashed_target.toarray()
# print(hashed_target)
# np.array(y)

# from sklearn.preprocessing import LabelEncoder

# # Example text target classes
# target_classes = ["red", "green", "blue", "red"]

# Encode labels
# encoder = LabelEncoder()
# encoded_classes = encoder.fit_transform(target_classes)
# print(encoded_classes)  # Output: [2 1 0 2]


[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
